build:
	docker build -t repo.treescale.com/bhorn/boot2root-clippy .

run: build
	docker run -it repo.treescale.com/bhorn/boot2root-clippy

push: build
	docker push repo.treescale.com/bhorn/boot2root-clippy
