build:
	docker build -t repo.treescale.com/bhorn/boot2root-inspector .

run: build
	docker run -it repo.treescale.com/bhorn/boot2root-inspector

push: build
	docker push repo.treescale.com/bhorn/boot2root-inspector
